Accelerators:
- label: 不选择
  value: None
- label: UU(未完成)
  value: UU
- label: ACGP(未完成)
  value: ACGP
- label: 和家亲
  value: Universal
Server: 1
Servers:
- label: 国际服
  value: 1
- label: 港澳台
  value: 2
Simulator:
  Accelerator: Universal
  Serial: emulator-5554
Socket:
  HideWindow: true
  NameSpace: /nkas
  Port: 5000
Version: v0.0.4
