Task:
  Commission:
    activate: true
    displayName: 委托
    name: Commission
    nextExecutionTime: 1678910400
  Conversation:
    activate: true
    displayName: 咨询
    name: Conversation
    nextExecutionTime: 1678910400
    nikkeList:
    - Snow_White
    - Centi
    - Guillotine
    - Anis
    - Sugar
    - Pepper
    - Dolla
    - Volume
    - Maxwell
  Daily:
    activate: true
    displayName: 每日任务
    equipmentUpgrade: false
    name: Daily
    nextExecutionTime: 1678910400
    nikkeUpgrade: true
  Destroy:
    activate: true
    displayName: 一举歼灭
    name: Destroy
    nextExecutionTime: 1678910400
  Event:
    activate: true
    currentEvent: 2
    difficulty: 0
    displayName: 活动
    event: 1-11
    finishAllEvent: true
    historyEvent:
    - label: BOW-WOW PARADISE
      path: /event_2
      type: 0
      value: 2
    - label: Chainsaw Man
      path: /event_1
      type: 1
      value: 1
    name: Event
    nextExecutionTime: 1678910400
    part: 2
  FreeStore:
    activate: true
    activate_arena_store: true
    arena_product_list: fire > selection_box
    displayName: 商店
    name: FreeStore
    nextExecutionTime: 1678910400
  Reward:
    activate: true
    arena: true
    displayName: 收获
    name: Reward
    nextExecutionTime: 1678910400
    recordTwiceTime: 1678910400
  RookieArena:
    activate: true
    displayName: 新人竞技场
    name: RookieArena
    nextExecutionTime: 1678910400
    refresh_chance: 3
    target: 1
    under: '1000'
  SimulationRoom:
    activate: true
    area: '2'
    difficulty: '5'
    displayName: 模拟室
    end_area: '2'
    name: SimulationRoom
    nextExecutionTime: 1678910400
  TribeTower:
    Elysion: true
    Missilis: true
    Pilgrim: true
    Tetra: true
    activate: true
    daily: true
    displayName: 企业塔
    name: TribeTower
    nextExecutionTime: 1678910400
