Task:
  Commission:
    activate: true
    displayName: 委托
    name: Commission
    nextExecutionTime: 1678737600
  Conversation:
    activate: true
    displayName: 咨询
    name: Conversation
    nextExecutionTime: 1678737600
    nikkeList:
    - Snow_White
    - Centi
    - Guillotine
    - Anis
    - Sugar
    - Pepper
    - Dolla
    - Volume
    - Maxwell
  Daily:
    activate: true
    displayName: 每日任务
    equipmentUpgrade: false
    name: Daily
    nextExecutionTime: 1678737600
    nikkeUpgrade: true
  Destroy:
    activate: true
    displayName: 一举歼灭
    name: Destroy
    nextExecutionTime: 1678737600
  Event:
    activate: true
    currentEvent: 1
    difficulty: 1
    displayName: 活动
    event: 1-9
    finishAllEvent: false
    historyEvent:
    - label: next
      path: /event_2
      type: 0
      value: 2
    - label: 电锯人
      path: /event_1
      type: 1
      value: 1
    name: Event
    nextExecutionTime: 1678737600
    part: 2
  FreeStore:
    activate: true
    displayName: 商店
    name: FreeStore
    nextExecutionTime: 1678737600
  Reward:
    activate: true
    arena: true
    displayName: 收获
    name: Reward
    nextExecutionTime: 1678737600
    recordTwiceTime: 1678737600
  RookieArena:
    activate: true
    displayName: 新人竞技场
    name: RookieArena
    nextExecutionTime: 1678737600
    refresh_chance: 3
    target: 1
    under: '0'
  SimulationRoom:
    activate: true
    area: '1'
    difficulty: '1'
    displayName: 模拟室
    end_area: '3'
    name: SimulationRoom
    nextExecutionTime: 1678737600
  TribeTower:
    Elysion: true
    Missilis: true
    Pilgrim: true
    Tetra: true
    activate: true
    daily: true
    displayName: 企业塔
    name: TribeTower
    nextExecutionTime: 1678737600
