Task:
  Commission:
    activate: true
    displayName: 委托
    name: Commission
    nextExecutionTime: 1678478400
  Conversation:
    activate: true
    displayName: 咨询
    name: Conversation
    nextExecutionTime: 1678478400
    nikkeList:
    - Snow_White
    - Centi
    - Anis
    - Sugar
    - Pepper
    - Dolla
    - Volume
    - Maxwell
    - Rupee
  Destroy:
    activate: true
    displayName: 一举歼灭
    name: Destroy
    nextExecutionTime: 1678478400
  Event:
    activate: true
    currentEvent: 1
    difficulty: 1
    displayName: 活动
    event: 1-9
    finishAllEvent: false
    historyEvent:
    - label: next
      path: /event_2
      type: 0
      value: 2
    - label: 电锯人
      path: /event_1
      type: 1
      value: 1
    name: Event
    nextExecutionTime: 1678478400
    part: 2
  FreeStore:
    activate: true
    displayName: 商店
    name: FreeStore
    nextExecutionTime: 1678478400
  Reward:
    activate: true
    displayName: 收获
    name: Reward
    nextExecutionTime: 1678478400
  RookieArena:
    activate: true
    displayName: 新人竞技场
    name: RookieArena
    nextExecutionTime: 1678478400
    target: 1
  SimulationRoom:
    activate: true
    area: '3'
    difficulty: '5'
    displayName: 模拟室
    end_area: '3'
    name: SimulationRoom
    nextExecutionTime: 1678478400
