Scheduler:
  Enable: false
  NextRun: 1989-12-27 00:00:00
  Command: NKAS
  SuccessInterval:
    value: 0
    display: hide
  FailureInterval:
    value: 120
    display: hide
  ServerUpdate:
    value: 04:00
    display: hide
Emulator:
  Serial:
    value: auto
    valuetype: str
  PackageName:
    value: com_proximabeta_nikke
    option: [ com_proximabeta_nikke, com_gamamobi_nikke, ]
  ScreenshotMethod:
    value: DroidCast
    option: [ DroidCast, ]
  ControlMethod:
    value: minitouch
    option: [ minitouch, ]
  AdbRestart: false
Reward:
  CollectSocialPoint: true
  CollectSpecialArenaPoint: true


