# ==================== Reward ====================

Reward:
  Scheduler:
    Enable: true

Destroy:
  Scheduler:
    Enable: true

Commission:
  Scheduler:
    Enable: true

RookieArena:
  Scheduler:
    Enable: true

Conversation:
  Scheduler:
    Enable: true