# ==================== Reward ====================

Reward:
  Scheduler:
    Enable: true

Destroy:
  Scheduler:
    Enable: false

Commission:
  Scheduler:
    Enable: false

RookieArena:
  Scheduler:
    Enable: false

Conversation:
  Scheduler:
    Enable: false

SimulationRoom:
  Scheduler:
    Enable: false

TribeTower:
  Scheduler:
    Enable: false

Daily:
  Scheduler:
    Enable: false

RubbishShop:
  Scheduler:
    Enable: false