# ==================== NKAS ====================

NKAS:
  - Emulator
  - Optimization
  - Notification

Restart:
  - Scheduler

# ==================== Reward ====================

Reward:
  - Scheduler
  - Reward

Destroy:
  - Scheduler

Commission:
  - Scheduler

# ==================== Daily ====================

Daily:
  - Scheduler
  - Daily

MissionPass:
  - Scheduler

Conversation:
  - Scheduler
  - Conversation

Shop:
  - Scheduler
  - GeneralShop
  - ArenaShop

RubbishShop:
  - Scheduler
  - RubbishShop

SimulationRoom:
  - Scheduler
  - Area

TribeTower:
  - Scheduler
  - Overcome

RookieArena:
  - Scheduler

# ==================== Event ====================

Event:
  - Scheduler
  - Event